# version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: "${CONTAINER_NAME}_postgres"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - setinc_net

  website:
    build:
      context: .
      args:
        - no-cache
    container_name: "${CONTAINER_NAME}_webapp"
    restart: always
    env_file: .env
    volumes:
      - .:/src  # This mounts your local project code into the container
      # You can add a pip cache volume here if needed:
      # - pip_cache:/root/.cache/pip
    ports:
      - "${CONTAINER_OUT_PORT}:8000"
    networks:
      - setinc_net
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    container_name: "${CONTAINER_NAME}_pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"  # You can access pgAdmin at http://localhost:5050
    depends_on:
      - postgres
    networks:
      - setinc_net    
  redis:
    image: redis:latest
    restart: always
    container_name: "${CONTAINER_NAME}_redis"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf  # Custom config
      - redis_data:/data                               # Persistent Redis data
    ports:
      - "6379:6379"
    networks:
      - setinc_net
networks:
  setinc_net:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  # pip_cache:
