# Generated by Django 3.0.8 on 2021-05-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210525_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='tracked_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
