# Generated by Django 3.0.8 on 2021-05-29 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210526_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tracked_time',
            field=models.DurationField(blank=True, default=datetime.timedelta),
        ),
    ]
