# Generated by Django 3.0.8 on 2021-05-31 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_defaultalarm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stopwatch',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
