# Generated by Django 3.0.8 on 2021-08-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='label',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
