# Generated by Django 3.0.8 on 2021-08-25 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alarm_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Task'),
        ),
    ]
