# Generated by Django 3.0.8 on 2021-08-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_task_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='active',
        ),
        migrations.AddField(
            model_name='alarm',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
