# Generated by Django 3.0.8 on 2021-09-03 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210826_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lap',
            name='stopwatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='api.Stopwatch'),
        ),
    ]
