# Generated by Django 3.0.8 on 2021-09-03 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210903_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stopwatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stopwatches', to=settings.AUTH_USER_MODEL),
        ),
    ]
