# Generated by Django 3.0.8 on 2023-06-07 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20220404_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='sound_level',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='defaultalarm',
            name='sound_level',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
