# Generated by Django 3.0.8 on 2024-02-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20230703_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_zone',
            field=models.CharField(default='Australia (GMT+11:00)', max_length=50),
        ),
    ]
