# Generated by Django 3.0.8 on 2024-03-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_task_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start_tracked_time',
            field=models.DateTimeField(blank=True, help_text='The time when the task was started.', null=True),
        ),
    ]
