# Generated by Django 3.0.8 on 2024-09-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20240321_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
