# Generated by Django 3.0.8 on 2025-06-16 22:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20240910_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='stopwatch',
            name='public_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='stopwatch',
            name='start_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stopwatch',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('started', 'Started'), ('stopped', 'Stopped'), ('reset', 'Reset')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='stopwatch',
            name='stopped_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
