# Generated by Django 3.0.8 on 2025-06-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20250616_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stopwatch',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stopwatch',
            name='stopped_time',
            field=models.DateTimeField(null=True),
        ),
    ]
