# Generated by Django 3.0.8 on 2025-06-17 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20250617_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='stopwatch',
            name='pre_time_diff',
            field=models.DurationField(blank=True, default=datetime.timedelta, null=True),
        ),
    ]
