# Generated by Django 3.0.8 on 2025-06-17 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_stopwatch_pre_time_diff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stopwatch',
            name='pre_time_diff',
        ),
        migrations.RemoveField(
            model_name='stopwatch',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='stopwatch',
            name='stopped_time',
        ),
        migrations.AddField(
            model_name='stopwatch',
            name='countdown_duration',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Duration for countdown stopwatch, if applicable.'),
        ),
    ]
