# Generated by Django 3.0.8 on 2025-06-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20250617_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='stopwatch',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
