# Generated by Django 3.0.8 on 2025-06-18 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_notes'),
        ('api', '0031_stopwatch_start_time'),
    ]

    operations = [
    ]
