APP_NAME = "setinc-ordex-dev"

STOPWATCH_LAPS = 5
COUNT_UNSUBSCRIBED_DATA = 5

VERIFICATION_CODE_LENGTH = 4

SOLOMON_TIME_ZONE = 'Solomon Islands (GMT+11:00)'
DEFAULT_TIME_ZONE = 'Australia (GMT+11:00)'
LOCAL_TIME = 'Local Time'


SOLOMON_ISLAND_CODE = '+677'

REMINDER_TIME = 5
REMINDER_DURATION_TIME = 3600

COUNT_UNSUBSCRIBED_ALARM = 5
COUNT_UNSUBSCRIBED_TASKS = 10
COUNT_UNSUBSCRIBED_LAPS = 3
COUNT_UNSUBSCRIBED_STOPWATCHES = 5
